spring:
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema:
                jdbc:
                    time_zone: UTC

scheduled_tasks:
    syncro:
        initial_delay: 5000
        fixed_delay: 18000

server:
    port: 8090

logging:
    config: file:./config/logback.xml

dev_server:
    port: 8080
    host: http://localhost