spring:
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
    jpa:
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema:
                jdbc:
                    time_zone: UTC
server:
    port: 8090

logging:
    config: file:./config/logback.xml

dev_server:
    port: 8080
    host: http://localhost