spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
server:
    port: 8090

logging:
    config: file:./config/logback.xml

dev_server:
    port: 8080
    host: http://localhost