FROM adoptopenjdk/openjdk11:alpine-jre
RUN addgroup -S appuser && adduser -S appuser -G appuser
USER appuser:appuser
WORKDIR /app
COPY ./app/app.jar /app/app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]